[2024-04-29T15:04:23.952+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T15:04:24.032+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Scrape_VnExpress.scrape_data manual__2024-04-29T08:04:02.443677+00:00 [queued]>
[2024-04-29T15:04:24.047+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Scrape_VnExpress.scrape_data manual__2024-04-29T08:04:02.443677+00:00 [queued]>
[2024-04-29T15:04:24.049+0700] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-29T15:04:24.085+0700] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): scrape_data> on 2024-04-29 08:04:02.443677+00:00
[2024-04-29T15:04:24.093+0700] {standard_task_runner.py:63} INFO - Started process 29352 to run task
[2024-04-29T15:04:24.102+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Scrape_VnExpress', 'scrape_data', 'manual__2024-04-29T08:04:02.443677+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/scape_news.py', '--cfg-path', '/tmp/tmp_jrl_3dh']
[2024-04-29T15:04:24.105+0700] {standard_task_runner.py:91} INFO - Job 3: Subtask scrape_data
[2024-04-29T15:04:24.287+0700] {task_command.py:426} INFO - Running <TaskInstance: Scrape_VnExpress.scrape_data manual__2024-04-29T08:04:02.443677+00:00 [running]> on host DESKTOP-BEALJ3H.
[2024-04-29T15:04:24.415+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Scrape_VnExpress' AIRFLOW_CTX_TASK_ID='scrape_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T08:04:02.443677+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-29T08:04:02.443677+00:00'
[2024-04-29T15:04:24.417+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T15:04:24.419+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T15:04:24.420+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow/plugins/crawl_news.py", line 9, in scrape_news
    topics_links = read_yaml('./data_scrape/crawler/links.yaml')
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow/plugins/data_scrape/crawler/utils.py", line 4, in read_yaml
    with open(filename, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: './data_scrape/crawler/links.yaml'
[2024-04-29T15:04:24.457+0700] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=Scrape_VnExpress, task_id=scrape_data, execution_date=20240429T080402, start_date=20240429T080424, end_date=20240429T080424
[2024-04-29T15:04:24.491+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task scrape_data ([Errno 2] No such file or directory: './data_scrape/crawler/links.yaml'; 29352)
[2024-04-29T15:04:24.517+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-29T15:04:24.568+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T15:04:24.590+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
